#!/usr/bin/env node
/**
 * Build DSH client entry (lib/client.js) from ordered src/client fragments.
 * DSH ModuleLoader loads a single file; this concatenates source modules
 * into that one factory. Run: npm run build:client
 * Pass --check to verify that lib/client.js is up-to-date without writing.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'src', 'client')
const outFile = join(root, 'lib', 'client.js')
const isCheck = process.argv.includes('--check')

const files = readdirSync(srcDir)
  .filter((name) => name.endsWith('.js'))
  .sort((a, b) => {
    // numeric prefix sort (00, 10, ..., 99, 100, ...)
    const na = Number.parseInt(a, 10)
    const nb = Number.parseInt(b, 10)
    if (Number.isFinite(na) && Number.isFinite(nb) && na !== nb) return na - nb
    return a.localeCompare(b)
  })

if (files.length === 0) {
  console.error('build-client: no fragments in src/client')
  process.exit(1)
}

const banner = `// GENERATED by scripts/build-client.mjs — do not edit. Sources: src/client/*
`

function extractLocaleKeys(src) {
  const keys = new Set()
  for (const line of src.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('//')) continue
    const m = trimmed.match(/^['"]([a-zA-Z0-9_.-]+)['"]\s*:/)
    if (m) keys.add(m[1])
  }
  return keys
}

function verifyLocales() {
  const enPath = join(srcDir, '110-locale-en.js')
  const zhPath = join(srcDir, '120-locale-zh.js')
  if (!existsSync(enPath) || !existsSync(zhPath)) {
    console.error('build-client: locale files missing in src/client')
    process.exit(1)
  }
  const enKeys = extractLocaleKeys(readFileSync(enPath, 'utf8'))
  const zhKeys = extractLocaleKeys(readFileSync(zhPath, 'utf8'))

  const diffEn = [...enKeys].filter((k) => !zhKeys.has(k))
  const diffZh = [...zhKeys].filter((k) => !enKeys.has(k))
  if (diffEn.length > 0 || diffZh.length > 0) {
    console.error('build-client: locale parity mismatch (#425):')
    if (diffEn.length > 0) console.error(`  in en but missing in zh (${diffEn.length}):`, diffEn.join(', '))
    if (diffZh.length > 0) console.error(`  in zh but missing in en (${diffZh.length}):`, diffZh.join(', '))
    process.exit(1)
  }

  const missingInLocale = new Set()
  for (const f of files) {
    const fc = readFileSync(join(srcDir, f), 'utf8')
    const matches = fc.matchAll(/\bt\(\s*['"]([a-zA-Z0-9_.-]+)['"]/g)
    for (const m of matches) {
      const key = m[1]
      if (!enKeys.has(key)) {
        missingInLocale.add(key)
      }
    }
  }

  if (missingInLocale.size > 0) {
    console.error('build-client: unlocalized t() literals found (#425):', [...missingInLocale].join(', '))
    process.exit(1)
  }

  console.log(`build-client: locales verified in sync (${enKeys.size} keys, full t() parity)`)
}

verifyLocales()

let body = ''
for (const name of files) {
  body += readFileSync(join(srcDir, name), 'utf8')
}

const expectedContent = banner + body

if (isCheck) {
  if (!existsSync(outFile)) {
    console.error('build-client: lib/client.js does not exist. Run npm run build:client')
    process.exit(1)
  }
  const currentContent = readFileSync(outFile, 'utf8')
  if (currentContent !== expectedContent) {
    console.error('build-client: lib/client.js is out of date with src/client/*. Run npm run build:client')
    process.exit(1)
  }
  console.log(`build-client: lib/client.js is in sync with ${files.length} fragments in src/client/*`)
  process.exit(0)
}

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, expectedContent, 'utf8')
console.log(`build-client: wrote lib/client.js from ${files.length} fragments (${body.length} bytes)`)
console.log(files.map((f) => `  - src/client/${f}`).join('\n'))
